version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - config/mongo.env

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    env_file:
      - config/mongo-express.env